# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_gcatbase_wrappers", use_symbols = TRUE, package_name = "gcatbase")

#' @docType package
#' @usage NULL
#' @useDynLib gcatbase, .registration = TRUE
NULL

r_all_tuples <- function(n, sigma) .Call(wrap__r_all_tuples, n, sigma)

